//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCCStudents.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCCStudents.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა პერიოდული ბექაპის გამორთვისას: {0}.
        /// </summary>
        internal static string Backup_Auto_Disable_Error {
            get {
                return ResourceManager.GetString("Backup_Auto_Disable_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერიოდული ბექაპი გამორთულია!.
        /// </summary>
        internal static string Backup_Auto_Disable_Success {
            get {
                return ResourceManager.GetString("Backup_Auto_Disable_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა პერიოდული ბექაპის ჩართვისას: {0}.
        /// </summary>
        internal static string Backup_Auto_Enable_Error {
            get {
                return ResourceManager.GetString("Backup_Auto_Enable_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერიოდული ბექაპი ჩართულია!.
        /// </summary>
        internal static string Backup_Auto_Enable_Success {
            get {
                return ResourceManager.GetString("Backup_Auto_Enable_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერიოდული ბექაპი გამორთულია.
        /// </summary>
        internal static string Backup_Auto_Status_Disabled {
            get {
                return ResourceManager.GetString("Backup_Auto_Status_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერიოდული ბექაპი ჩართულია (ინტერვალი: {0} საათი).
        /// </summary>
        internal static string Backup_Auto_Status_Enabled {
            get {
                return ResourceManager.GetString("Backup_Auto_Status_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შექმნის თარიღი.
        /// </summary>
        internal static string Backup_Column_CreationTime {
            get {
                return ResourceManager.GetString("Backup_Column_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის სახელი.
        /// </summary>
        internal static string Backup_Column_FileName {
            get {
                return ResourceManager.GetString("Backup_Column_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის მისამართი.
        /// </summary>
        internal static string Backup_Column_FilePath {
            get {
                return ResourceManager.GetString("Backup_Column_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის ზომა.
        /// </summary>
        internal static string Backup_Column_FileSize {
            get {
                return ResourceManager.GetString("Backup_Column_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ბექაპის შექმნისას: {0}.
        /// </summary>
        internal static string Backup_Create_Error {
            get {
                return ResourceManager.GetString("Backup_Create_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბექაპის შექმნა ვერ მოხერხდა!.
        /// </summary>
        internal static string Backup_Create_Fail {
            get {
                return ResourceManager.GetString("Backup_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს ბექაპის შექმნა....
        /// </summary>
        internal static string Backup_Create_Status {
            get {
                return ResourceManager.GetString("Backup_Create_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბექაპი წარმატებით შეიქმნა!.
        /// </summary>
        internal static string Backup_Create_Success {
            get {
                return ResourceManager.GetString("Backup_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გსურთ ბექაპის წაშლა?{0}{0}ფაილი: {1}{0}თარიღი: {2}.
        /// </summary>
        internal static string Backup_Delete_ConfirmText {
            get {
                return ResourceManager.GetString("Backup_Delete_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბექაპის წაშლა.
        /// </summary>
        internal static string Backup_Delete_ConfirmTitle {
            get {
                return ResourceManager.GetString("Backup_Delete_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ბექაპის წაშლისას: {0}.
        /// </summary>
        internal static string Backup_Delete_Error {
            get {
                return ResourceManager.GetString("Backup_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გთხოვთ, აირჩიოთ ბექაპი წასაშლელად!.
        /// </summary>
        internal static string Backup_Delete_NoSelection {
            get {
                return ResourceManager.GetString("Backup_Delete_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბექაპი წარმატებით წაიშალა!.
        /// </summary>
        internal static string Backup_Delete_Success {
            get {
                return ResourceManager.GetString("Backup_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ფაილის კოპირებისას: {0}.
        /// </summary>
        internal static string Backup_File_Copy_Error {
            get {
                return ResourceManager.GetString("Backup_File_Copy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ფაილის ინფორმაციის ჩვენებისას: {0}.
        /// </summary>
        internal static string Backup_File_Info_Error {
            get {
                return ResourceManager.GetString("Backup_File_Info_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის სახელი: {0}{1}სრული მისამართი: {2}{1}ზომა: {3}{1}შექმნის თარიღი: {4}{1}ბოლო ცვლილება: {5}{1}ბოლო წვდომა: {6}.
        /// </summary>
        internal static string Backup_File_Info_Text {
            get {
                return ResourceManager.GetString("Backup_File_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის ინფორმაცია.
        /// </summary>
        internal static string Backup_File_Info_Title {
            get {
                return ResourceManager.GetString("Backup_File_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილი ვერ მოიძებნა!.
        /// </summary>
        internal static string Backup_File_NotFound {
            get {
                return ResourceManager.GetString("Backup_File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ფაილის გახსნისას: {0}.
        /// </summary>
        internal static string Backup_File_Open_Error {
            get {
                return ResourceManager.GetString("Backup_File_Open_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ფაილის შიგთავსის ჩვენებისას: {0}.
        /// </summary>
        internal static string Backup_File_ViewContent_Error {
            get {
                return ResourceManager.GetString("Backup_File_ViewContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბოლო ბექაპი: {0}.
        /// </summary>
        internal static string Backup_LastBackup {
            get {
                return ResourceManager.GetString("Backup_LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბექაპი ჯერ არ არის შექმნილი.
        /// </summary>
        internal static string Backup_LastBackup_None {
            get {
                return ResourceManager.GetString("Backup_LastBackup_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის კოპირება.
        /// </summary>
        internal static string Backup_Menu_CopyFile {
            get {
                return ResourceManager.GetString("Backup_Menu_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის ინფორმაცია.
        /// </summary>
        internal static string Backup_Menu_FileInfo {
            get {
                return ResourceManager.GetString("Backup_Menu_FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტექსტური რედაქტორით გახსნა.
        /// </summary>
        internal static string Backup_Menu_OpenInEditor {
            get {
                return ResourceManager.GetString("Backup_Menu_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შიგთავსის ნახვა.
        /// </summary>
        internal static string Backup_Menu_ViewContent {
            get {
                return ResourceManager.GetString("Backup_Menu_ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა საქაღალდის გახსნისას: {0}.
        /// </summary>
        internal static string Backup_OpenFolder_Error {
            get {
                return ResourceManager.GetString("Backup_OpenFolder_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გსურთ ბაზის აღდგენა არჩეული ბექაპიდან?{0}{0}ფაილი: {1}{0}თარიღი: {2}{0}{0}გაფრთხილება: ეს ოპერაცია შეცვლის მიმდინარე მონაცემებს!.
        /// </summary>
        internal static string Backup_Restore_ConfirmText {
            get {
                return ResourceManager.GetString("Backup_Restore_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბაზის აღდგენა.
        /// </summary>
        internal static string Backup_Restore_ConfirmTitle {
            get {
                return ResourceManager.GetString("Backup_Restore_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ბაზის აღდგენისას: {0}.
        /// </summary>
        internal static string Backup_Restore_Error {
            get {
                return ResourceManager.GetString("Backup_Restore_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბაზის აღდგენა ვერ მოხერხდა!.
        /// </summary>
        internal static string Backup_Restore_Fail {
            get {
                return ResourceManager.GetString("Backup_Restore_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გთხოვთ, აირჩიოთ ბექაპი სიიდან!.
        /// </summary>
        internal static string Backup_Restore_NoSelection {
            get {
                return ResourceManager.GetString("Backup_Restore_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს ბაზის აღდგენა....
        /// </summary>
        internal static string Backup_Restore_Status {
            get {
                return ResourceManager.GetString("Backup_Restore_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბაზა წარმატებით აღდგა!.
        /// </summary>
        internal static string Backup_Restore_Success {
            get {
                return ResourceManager.GetString("Backup_Restore_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნაპოვნია {0} ბექაპი (ფილტრი: {1} - {2}).
        /// </summary>
        internal static string Backup_Status_FilteredCount {
            get {
                return ResourceManager.GetString("Backup_Status_FilteredCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნაპოვნია {0} ბექაპი.
        /// </summary>
        internal static string Backup_Status_LoadedCount {
            get {
                return ResourceManager.GetString("Backup_Status_LoadedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა ბექაპების ჩატვირთვის დროს.
        /// </summary>
        internal static string Backup_Status_LoadError {
            get {
                return ResourceManager.GetString("Backup_Status_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს ბექაპების ჩატვირთვა....
        /// </summary>
        internal static string Backup_Status_LoadingBackups {
            get {
                return ResourceManager.GetString("Backup_Status_LoadingBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბექაპის შიგთავსი - {0}.
        /// </summary>
        internal static string Backup_ViewContent_Title {
            get {
                return ResourceManager.GetString("Backup_ViewContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სარეზერვო ასლები.
        /// </summary>
        internal static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეცდომა.
        /// </summary>
        internal static string Common_ErrorTitle {
            get {
                return ResourceManager.GetString("Common_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ინფორმაცია.
        /// </summary>
        internal static string Common_InfoTitle {
            get {
                return ResourceManager.GetString("Common_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაფრთხილება.
        /// </summary>
        internal static string Common_WarningTitle {
            get {
                return ResourceManager.GetString("Common_WarningTitle", resourceCulture);
            }
        }
    }
}
