//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCCStudents.Presentation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bd1199c025234dfab9da6331d6c5be20")]
        public string SmsApiKey {
            get {
                return ((string)(this["SmsApiKey"]));
            }
            set {
                this["SmsApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("მოგესალმებით, თქვენ რეგისტრირდით")]
        public string SmsText_Registration {
            get {
                return ((string)(this["SmsText_Registration"]));
            }
            set {
                this["SmsText_Registration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("გადახდა შესრულებულია ✅")]
        public string SmsText_Payment {
            get {
                return ((string)(this["SmsText_Payment"]));
            }
            set {
                this["SmsText_Payment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("მოგახსენებთ, რომ გადახდის თარიღი ახლოვდება")]
        public string SmsText_UpcomingReminder {
            get {
                return ((string)(this["SmsText_UpcomingReminder"]));
            }
            set {
                this["SmsText_UpcomingReminder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("გადახდის ვადა გადავიდა ⚠️")]
        public string SmsText_OverdueReminder {
            get {
                return ((string)(this["SmsText_OverdueReminder"]));
            }
            set {
                this["SmsText_OverdueReminder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool SmsEnabled {
            get {
                return ((bool)(this["SmsEnabled"]));
            }
            set {
                this["SmsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool IsTestDb {
            get {
                return ((bool)(this["IsTestDb"]));
            }
            set {
                this["IsTestDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupDirectory {
            get {
                return ((string)(this["BackupDirectory"]));
            }
            set {
                this["BackupDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int BackupIntervalHours {
            get {
                return ((int)(this["BackupIntervalHours"]));
            }
            set {
                this["BackupIntervalHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1440")]
        public int BackupIntervalMinutes {
            get {
                return ((int)(this["BackupIntervalMinutes"]));
            }
            set {
                this["BackupIntervalMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MaxBackupFiles {
            get {
                return ((int)(this["MaxBackupFiles"]));
            }
            set {
                this["MaxBackupFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MySqlDumpPath {
            get {
                return ((string)(this["MySqlDumpPath"]));
            }
            set {
                this["MySqlDumpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupUsername {
            get {
                return ((string)(this["BackupUsername"]));
            }
            set {
                this["BackupUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupPassword {
            get {
                return ((string)(this["BackupPassword"]));
            }
            set {
                this["BackupPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime LastBackupTime {
            get {
                return ((global::System.DateTime)(this["LastBackupTime"]));
            }
            set {
                this["LastBackupTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Port=3307;Database=bccstudents_local;User=root;Password=Admin.25" +
            ";SslMode=Preferred;CharSet=utf8mb4;")]
        public string LocalMySqlConnectionString {
            get {
                return ((string)(this["LocalMySqlConnectionString"]));
            }
            set {
                this["LocalMySqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=bccenter.ge;Port=3306;Database=bccenter_SchoolManagement;User=bccenter_sch" +
            "oolAdmin25;Password=@wh0X0kpPHey")]
        public string ServerMySqlConnectionString {
            get {
                return ((string)(this["ServerMySqlConnectionString"]));
            }
            set {
                this["ServerMySqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Port=3307;Database=bccstudents_local_test;User=root;Password=Adm" +
            "in.25;SslMode=Preferred;CharSet=utf8mb4;")]
        public string LocalMySqlConnectionString_Test {
            get {
                return ((string)(this["LocalMySqlConnectionString_Test"]));
            }
            set {
                this["LocalMySqlConnectionString_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=bccenter.ge;Port=3306;Database=bccenter_SchoolManagement_Test;User=bccente" +
            "r_schoolAdmin25;Password=@wh0X0kpPHey")]
        public string ServerMySqlConnectionString_Test {
            get {
                return ((string)(this["ServerMySqlConnectionString_Test"]));
            }
            set {
                this["ServerMySqlConnectionString_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin123")]
        public string AdminCode {
            get {
                return ((string)(this["AdminCode"]));
            }
            set {
                this["AdminCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFullBalanceForAutoPayment {
            get {
                return ((bool)(this["UseFullBalanceForAutoPayment"]));
            }
            set {
                this["UseFullBalanceForAutoPayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoBackupEnabled {
            get {
                return ((bool)(this["AutoBackupEnabled"]));
            }
            set {
                this["AutoBackupEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DbChangedSinceLastBackup {
            get {
                return ((bool)(this["DbChangedSinceLastBackup"]));
            }
            set {
                this["DbChangedSinceLastBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLocalDb {
            get {
                return ((bool)(this["UseLocalDb"]));
            }
            set {
                this["UseLocalDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDownstreamSyncEnabled {
            get {
                return ((bool)(this["AutoDownstreamSyncEnabled"]));
            }
            set {
                this["AutoDownstreamSyncEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpstreamSyncEnabled {
            get {
                return ((bool)(this["AutoUpstreamSyncEnabled"]));
            }
            set {
                this["AutoUpstreamSyncEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdateEnabled {
            get {
                return ((bool)(this["AutoUpdateEnabled"]));
            }
            set {
                this["AutoUpdateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnVisibilitySettings {
            get {
                return ((string)(this["ColumnVisibilitySettings"]));
            }
            set {
                this["ColumnVisibilitySettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnWidthsSettings {
            get {
                return ((string)(this["ColumnWidthsSettings"]));
            }
            set {
                this["ColumnWidthsSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableCustomSubGroupMaxStudents {
            get {
                return ((bool)(this["EnableCustomSubGroupMaxStudents"]));
            }
            set {
                this["EnableCustomSubGroupMaxStudents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsedUsernames {
            get {
                return ((string)(this["UsedUsernames"]));
            }
            set {
                this["UsedUsernames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowPartialPayments {
            get {
                return ((bool)(this["AllowPartialPayments"]));
            }
            set {
                this["AllowPartialPayments"] = value;
            }
        }
    }
}
