CREATE TABLE IF NOT EXISTS Users (
  Id INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(255) NOT NULL,
  FullName VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(255) DEFAULT NULL,
  Password VARCHAR(255) DEFAULT NULL,
  Role VARCHAR(50) DEFAULT NULL,
  CreatedAt DATETIME DEFAULT NULL,
  LastLogin DATETIME DEFAULT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SystemConfig (
  Id INT NOT NULL AUTO_INCREMENT,
  `Key` VARCHAR(100) NOT NULL,
  `Value` TEXT NOT NULL,
  `Type` VARCHAR(50) NOT NULL DEFAULT 'String',
  Description VARCHAR(255) DEFAULT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY ux_systemconfig_key (`Key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Groups (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Teacher VARCHAR(255) DEFAULT NULL,
  ContractTemplatePath VARCHAR(500) DEFAULT NULL,
  Status TINYINT(1) NOT NULL DEFAULT 1,
  StudentCount INT NOT NULL DEFAULT 0,
  MaxStudents INT NOT NULL DEFAULT 0,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE KEY ux_groups_name (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SubGroups (
  Id INT NOT NULL AUTO_INCREMENT,
  GroupId INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  TuitionFee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  StudentCount INT NOT NULL DEFAULT 0,
  MaxStudents INT NOT NULL DEFAULT 0,
  Status TINYINT(1) NOT NULL DEFAULT 1,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  KEY idx_subgroups_group (GroupId),
  CONSTRAINT fk_subgroups_group FOREIGN KEY (GroupId) REFERENCES Groups (Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Students (
  Id INT NOT NULL AUTO_INCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Age INT NOT NULL,
  ParentName TEXT NOT NULL,
  PhoneNumber TEXT NOT NULL,
  Id_Numb BIGINT NOT NULL,
  Address TEXT NOT NULL,
  RegistrationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  StudentCode VARCHAR(25) DEFAULT NULL,
  Status TINYINT(1) NOT NULL DEFAULT 1,
  IdCardPath TEXT,
  AdditionalDocsPath TEXT,
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  Balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Info TEXT,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE KEY ux_students_code (StudentCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS StudentGroups (
  Id INT NOT NULL AUTO_INCREMENT,
  StudentId INT NOT NULL,
  GroupId INT NOT NULL,
  SubGroupId INT DEFAULT NULL,
  PaymentStatus VARCHAR(50) DEFAULT NULL,
  DateOfPayment DATETIME DEFAULT NULL,
  Price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Discount DOUBLE NOT NULL DEFAULT 0,
  Status TINYINT(1) NOT NULL DEFAULT 1,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  KEY idx_studentgroups_student (StudentId),
  KEY idx_studentgroups_group (GroupId),
  KEY idx_studentgroups_subgroup (SubGroupId),
  CONSTRAINT fk_studentgroups_student FOREIGN KEY (StudentId) REFERENCES Students (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_studentgroups_group FOREIGN KEY (GroupId) REFERENCES Groups (Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS StudentSubGroups (
  Id INT NOT NULL AUTO_INCREMENT,
  StudentId INT NOT NULL,
  GroupId INT NOT NULL,
  SubGroupId INT NOT NULL,
  PaymentStatus VARCHAR(50) DEFAULT NULL,
  DateOfPayment DATETIME DEFAULT NULL,
  Price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Discount DOUBLE NOT NULL DEFAULT 0,
  Status TINYINT(1) NOT NULL DEFAULT 1,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  KEY idx_studentsubgroups_student (StudentId),
  KEY idx_studentsubgroups_group (GroupId),
  KEY idx_studentsubgroups_subgroup (SubGroupId),
  CONSTRAINT fk_studentsubgroups_student FOREIGN KEY (StudentId) REFERENCES Students (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_studentsubgroups_group FOREIGN KEY (GroupId) REFERENCES Groups (Id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_studentsubgroups_subgroup FOREIGN KEY (SubGroupId) REFERENCES SubGroups (Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Payments (
  Id INT NOT NULL AUTO_INCREMENT,
  StudentId INT DEFAULT NULL,
  GroupId INT NOT NULL,
  Amount DECIMAL(10,2) NOT NULL,
  PaymentDate DATETIME NOT NULL,
  PaymentStatus VARCHAR(50) DEFAULT NULL,
  Description VARCHAR(500) DEFAULT NULL,
  PayerName VARCHAR(255) DEFAULT NULL,
  PersonalId BIGINT DEFAULT NULL,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ImportedFilesLog (
  Id INT NOT NULL AUTO_INCREMENT,
  FilePath VARCHAR(500) NOT NULL,
  FileName VARCHAR(255) NOT NULL,
  FileHash VARCHAR(64) NOT NULL,
  FileSize BIGINT NOT NULL,
  ImportedAt DATETIME NOT NULL,
  ImportedBy VARCHAR(100) NOT NULL,
  ComputerName VARCHAR(100) NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY ux_importedfiles_hash (FileHash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ImportedPaymentsLog (
  Id INT NOT NULL AUTO_INCREMENT,
  PaymentDate DATETIME NOT NULL,
  Amount DECIMAL(10,2) NOT NULL,
  PersonalId BIGINT DEFAULT NULL,
  Description VARCHAR(500) DEFAULT NULL,
  ImportSource VARCHAR(100) DEFAULT NULL,
  CreatedAt DATETIME NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FailedPayments (
  Id INT NOT NULL AUTO_INCREMENT,
  RowNumber INT NOT NULL,
  PaymentDate DATETIME NOT NULL,
  Amount DECIMAL(10,2) NOT NULL,
  PersonalId BIGINT DEFAULT NULL,
  Description VARCHAR(500) DEFAULT NULL,
  Reason VARCHAR(255) NOT NULL,
  CreatedAt DATETIME NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FailedStudentImports (
  Id INT NOT NULL AUTO_INCREMENT,
  SheetName VARCHAR(255) DEFAULT NULL,
  RowNumber INT NOT NULL DEFAULT 0,
  FirstName VARCHAR(255) DEFAULT NULL,
  LastName VARCHAR(255) DEFAULT NULL,
  Age INT DEFAULT NULL,
  ParentName VARCHAR(255) DEFAULT NULL,
  PhoneNumber VARCHAR(50) DEFAULT NULL,
  Id_Numb BIGINT DEFAULT NULL,
  Address VARCHAR(500) DEFAULT NULL,
  TuitionFee DECIMAL(10,2) DEFAULT NULL,
  Discount DOUBLE DEFAULT NULL,
  DateOfPayment DATETIME DEFAULT NULL,
  RegistrationDate DATETIME DEFAULT NULL,
  StudentCode VARCHAR(50) DEFAULT NULL,
  SubGroup INT DEFAULT NULL,
  GroupId INT DEFAULT NULL,
  GroupName VARCHAR(255) DEFAULT NULL,
  ErrorMessage TEXT NOT NULL,
  ImportDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  User_Id INT DEFAULT NULL,
  ExcelFileName VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (Id),
  KEY idx_failedimports_sheet_row (SheetName, RowNumber),
  KEY idx_failedimports_import_date (ImportDate),
  KEY idx_failedimports_user_id (User_Id),
  KEY idx_failedimports_group_id (GroupId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PendingStudents (
  Id INT NOT NULL,
  FirstName VARCHAR(255) DEFAULT NULL,
  LastName VARCHAR(255) DEFAULT NULL,
  Age INT DEFAULT NULL,
  ParentName VARCHAR(255) DEFAULT NULL,
  PhoneNumber VARCHAR(50) DEFAULT NULL,
  Id_Numb BIGINT DEFAULT NULL,
  Address VARCHAR(500) DEFAULT NULL,
  TuitionFee DECIMAL(10,2) DEFAULT NULL,
  DiscountPercentage DECIMAL(10,2) DEFAULT NULL,
  StudentCode VARCHAR(50) DEFAULT NULL,
  IdCardPath VARCHAR(500) DEFAULT NULL,
  AdditionalDocsPath VARCHAR(500) DEFAULT NULL,
  user_id INT DEFAULT NULL,
  CreatedAt DATETIME DEFAULT NULL,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PendingStudentGroups (
  Id INT NOT NULL,
  StudentId INT NOT NULL,
  PendingStudentId INT DEFAULT NULL,
  GroupId INT NOT NULL,
  CreatedAt DATETIME DEFAULT NULL,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PendingStudentSubGroups (
  Id INT NOT NULL,
  StudentId INT NOT NULL,
  GroupId INT NOT NULL,
  SubGroupId INT NOT NULL,
  CreatedAt DATETIME DEFAULT NULL,
  UpdatedAt DATETIME DEFAULT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SyncOutbox (
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  TableName VARCHAR(64) NOT NULL,
  RecordId INT NULL,
  RecordKey VARCHAR(128) NULL,
  Operation VARCHAR(16) NOT NULL,
  PayloadJson MEDIUMTEXT NULL,
  OccurredAt DATETIME NOT NULL,
  Attempts INT NOT NULL DEFAULT 0,
  LastError TEXT NULL,
  Status TINYINT NOT NULL DEFAULT 0,
  LastRetryTime DATETIME NULL,
  INDEX idx_outbox_status (Status, OccurredAt),
  INDEX idx_outbox_table (TableName, OccurredAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SyncState (
  TableName VARCHAR(64) PRIMARY KEY,
  LastSyncedAt DATETIME NULL,
  LastSyncedId INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
